feat: initial Button component
MetaMask/metamask-design-system pull request #299
Opened 2024-12-14 00:12 UTC by georgewrmarshall

## Description

This PR unifies the separate button variants (Primary, Secondary, Link) into a single Button component for better maintainability and consistent API.

## Related issues

Fixes: #144

## Manual testing steps

1. Run Storybook (`yarn storybook`)
2. Navigate to the Button component
3. Test all variants (Primary, Secondary, Link)
4. Verify all features work across variants:
   - Sizes
   - Icons
   - Loading states
   - Disabled states
   - Danger variants
   - Inverse variants (Primary/Secondary only)

## Screenshots/Recordings

N/A - Component behavior remains visually unchanged

## Pre-merge author checklist

- [x] I've followed MetaMask Contributor Docs
- [x] I've completed the PR template
- [x] I've included tests (100% coverage for new Button component)
- [x] I've documented code using JSDoc format

## Pre-merge reviewer checklist

- [ ] I've manually tested the PR
- [ ] I confirm this PR addresses all acceptance criteria" \

2025-01-08 22:29 UTC, georgewrmarshall commented on packages/design-system-react/src/components/button/README.mdx
> +A versatile button component that supports multiple variants: Primary, Secondary, and Link.
Update this to align with insight report

2025-01-24 01:23 UTC, georgewrmarshall commented on packages/design-system-react/src/components/index.ts
> +export type { ButtonProps } from './button';
Simplifies imports in root index

2025-01-24 18:30 UTC, brianacnguyen requested changes
1 small question

2025-01-24 18:30 UTC, brianacnguyen commented on packages/design-system-react/src/components/button/Button.types.ts
> +);
so you cant use ref with Button?

2025-01-24 19:21 UTC, georgewrmarshall commented on packages/design-system-react/src/components/button/Button.types.ts
> +);
Good question! We can definitely use refs with Button! We're using React's `forwardRef` pattern which explicitly enables ref support. The `Omit<..., 'ref'>` in the types is specifically there to avoid type conflicts since `forwardRef` handles the ref prop separately from other props.

You can see this working in our test suite under the "Ref Forwarding" describe block:
https://github.com/MetaMask/metamask-design-system/blob/db1c861ecc071bf554af791c0aceab40bbbbe56c/packages/design-system-react/src/components/button/Button.test.tsx#L238-L263

2025-01-24 19:33 UTC, brianacnguyen approved these changes

2025-01-24 19:40 UTC, merged